import prestation from './prestation'
import homePage from './homePage.ts'
import serviceCard from './serviceCard.ts'
import servicesSection from './servicesSection.ts'
import statsSection from './statsSection.ts'
import aboutSection from './aboutSection.ts'
import howItWorksSection from './howItWorksSection.ts'
import aboutPage from './aboutPage.ts'
import valuesSection from './valuesSection.ts'
import timelineSection from './timelineSection.ts'
import ctaSection from './ctaSection.ts'
import footer from './footer.ts'
import contactPage from './contactPage.ts'
import testimonialsSection from './testimonialsSection.ts'
import zoneIntervention from './objects/zoneIntervention.ts'
import zonesInterventionSection from './zonesInterventionSection.ts'
import faqItem from './objects/faqItem.ts'
import faqSection from './faqSection.ts'
import prestationsPage from './prestationsPage.ts'

export const schemaTypes = [prestation, homePage, serviceCard, servicesSection, statsSection, aboutSection, howItWorksSection, aboutPage, valuesSection, timelineSection, ctaSection, footer, contactPage, testimonialsSection, zoneIntervention, zonesInterventionSection, faqItem, faqSection, prestationsPage]